name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Get version number from release
      id: get-version
      run:
        TAG=${GITHUB_REF#refs/tags/}
        echo "VERSION_WITHOUT_V=${TAG#v}" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Check version number
      run: |
        PACKAGE_VERSION=$(python setup.py --version)
        RELEASE_VERSION=${{ steps.get-version.outputs.VERSION_WITHOUT_V }}
        if [ $PACKAGE_VERSION != $RELEASE_VERSION ]; then
          echo "Package version $PACKAGE_VERSION does not match release version $RELEASE_VERSION"
          exit 1
        fi
    - name: Build
      run: |
        python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
